import { createServer, request, type Server } from 'node:http';
import { readFileSync } from 'node:fs';
import { once } from 'node:events';
import { afterEach, expect, it } from 'vitest';
import { WebSocket } from 'ws';
import { startFrontDoor } from './front-door.mjs';
import { createMobileRouting } from './mobile-routing.mjs';

const token = 'm'.repeat(43);
const env = { MOBILE_RELAY_TOKEN: token, MOBILE_RELAY_PUBLIC_URL: 'https://mobile.example' };
const cleanup: Array<() => unknown | Promise<unknown>> = [];
afterEach(async () => { for (const close of cleanup.splice(0).reverse()) await close(); });

it('ships the identical mobile relay implementation in the website-only Docker context', () => {
  for (const file of ['server.mjs', 'protocol.mjs']) {
    const source = readFileSync(new URL(`../../services/mobile-relay/${file}`, import.meta.url), 'utf8');
    const copy = readFileSync(new URL(`./mobile/${file}`, import.meta.url), 'utf8');
    expect(copy).toBe('// Generated by scripts/sync-mobile-relay.mjs. Edit services/mobile-relay instead.\n' + source);
  }
});
it('is optional and requires both a dedicated secret and an HTTPS origin', () => {
  expect(createMobileRouting({})).toBeNull();
  expect(createMobileRouting({ ZCC_RELAY_TOKEN: token })).toBeNull();
  expect(() => createMobileRouting({ MOBILE_RELAY_TOKEN: token })).toThrow('Set both');
  expect(() => createMobileRouting({ MOBILE_RELAY_PUBLIC_URL: 'https://mobile.example' })).toThrow('Set both');
  expect(() => createMobileRouting({ ...env, MOBILE_RELAY_PUBLIC_URL: 'http://mobile.example' })).toThrow();
});
it('routes phone endpoints and the exact session cookie without consuming public website or pairing routes', () => {
  const router = createMobileRouting(env)!; cleanup.push(router.close);
  const matches = (url: string, cookie?: string, host = 'mobile.example') => router.matches({ url, headers: { host, cookie } });
  for (const path of ['/_mobile/pair', '/_relay/connect', '/api/v1/health', '/ws', '/ws/?x=1']) expect(matches(path)).toBe(true);
  for (const path of ['/', '/docs', '/api/auth/github/login', '/api/tokens', '/_next/static/a.js', '/install.sh', '/_zcc/relay', '/internal/hosts/ws', '/api/v10', '/ws-other']) expect(matches(path)).toBe(false);
  expect(matches('/', 'foo=bar; zcc_mobile_session=abc')).toBe(true);
  expect(matches('/', 'other_zcc_mobile_session=abc')).toBe(false);
  expect(matches('/', 'zcc_mobile_session=abc', 'website.example')).toBe(false);
  expect(matches('/_relay/connect', undefined, 'evil.example')).toBe(false);
});

async function listen(server: Server) { server.listen(0, '127.0.0.1'); await once(server, 'listening'); return (server.address() as { port: number }).port; }
function get(port: number, path: string, headers = {}) {
  return new Promise<{ status: number; body: string }>((resolve, reject) => {
    const req = request({ hostname: '127.0.0.1', port, path, headers: { host: 'mobile.example', 'x-forwarded-proto': 'https', ...headers } }, res => {
      const chunks: Buffer[] = []; res.on('data', chunk => chunks.push(chunk)); res.on('end', () => resolve({ status: res.statusCode!, body: Buffer.concat(chunks).toString() }));
    }); req.on('error', reject); req.end();
  });
}
it('shares the real front door listener, keeps the website available and closes its tunnel on shutdown', async () => {
  const next = createServer((_req, res) => res.end('website'));
  const nextPort = await listen(next);
  cleanup.push(() => new Promise<void>(resolve => next.close(() => resolve())));
  const door = await startFrontDoor({ port: 0, host: '127.0.0.1', env, spawnNext: false, nextOrigin: `http://127.0.0.1:${nextPort}` });
  cleanup.push(() => door.close());
  expect(await get(door.port, '/')).toEqual({ status: 200, body: 'website' });
  expect((await get(door.port, '/install.sh')).status).toBe(503);
  expect((await get(door.port, '/_mobile/pair')).status).toBe(503);
  const ws = new WebSocket(`ws://127.0.0.1:${door.port}/_relay/connect`, { headers: { host: 'mobile.example', 'x-forwarded-proto': 'https', authorization: `Bearer ${token}` } });
  cleanup.push(() => ws.terminate());
  await once(ws, 'open');
  ws.on('message', raw => {
    const frame = JSON.parse(raw.toString());
    if (frame.type !== 'request') return;
    ws.send(JSON.stringify({ type: 'response', id: frame.id, status: 401, headers: { 'content-type': 'application/json' } }));
    ws.send(JSON.stringify({ type: 'response-data', id: frame.id, data: Buffer.from('{"error":"pair first"}').toString('base64') }));
    ws.send(JSON.stringify({ type: 'response-end', id: frame.id }));
  });
  expect((await get(door.port, '/_relay/health')).body).toContain('"connected":true');
  expect((await get(door.port, '/', { cookie: 'zcc_mobile_session=invalid' })).status).toBe(401);
  expect((await get(door.port, '/', { cookie: 'website_auth=ok' })).body).toBe('website');
  expect((await get(door.port, '/_mobile/health', { 'x-forwarded-proto': 'http' })).status).toBe(403);
});
