import { afterEach, beforeEach, expect, it } from 'vitest';
import { createHmac } from 'node:crypto';
import { openConnectDatabase } from './database.mjs';
import { createRegistry, digest } from './registry.mjs';
import { createConnectApi } from './http.mjs';
let db: any, registry: any, api: any;
let now = Date.now();
const origin = 'https://example.com';
const cookie = `zcc_session=session.${createHmac('sha256', 'fixture').update('session').digest('base64url')}`;
const owner = { cookie, origin };
const call = (path: string, body?: unknown, headers = {}) => api.dispatch(new Request(`${origin}/api/connect/phone/${path}`, { method: body === undefined ? 'GET' : 'POST', headers: { 'content-type': 'application/json', ...headers }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }));
beforeEach(async () => {
  now = Date.now(); db = await openConnectDatabase(':memory:', { production: false }); await db.migrate();
  await db.query('CREATE TABLE users(id TEXT PRIMARY KEY,github_login TEXT)');
  await db.query('CREATE TABLE sessions(id TEXT PRIMARY KEY,user_id TEXT,expires_at BIGINT)');
  await db.query('INSERT INTO users VALUES($1,$1)', ['alice']);
  await db.query('INSERT INTO sessions VALUES($1,$2,$3)', ['session', 'alice', now + 3600_000]);
  registry = createRegistry(db, { domain: 'connect.example.com', accountUrl: origin, now: () => now, limit: 1 });
  api = createConnectApi({ registry, db, sessionSecret: 'fixture', now: () => now });
});
afterEach(() => db.close());
it('signs in a phone without a computer, keeps secrets out of browser approval, and retries delivery without duplicate grants', async () => {
  const start = await (await call('start', { name: ' My iPhone ' })).json();
  expect(start.verificationUrl).toBe(`${origin}/connect/?phone=${start.userCode}`);
  expect(await (await call('poll', { deviceCode: start.deviceCode })).json()).toEqual({ pending: true });
  const info = await (await call(`info?code=${start.userCode}`, undefined, owner)).json();
  expect(info).toEqual({ name: 'My iPhone', approved: false, denied: false });
  expect(JSON.stringify(info)).not.toContain(start.deviceCode);
  expect((await call('approve', { code: start.userCode, approved: true }, owner)).status).toBe(200);
  const [first, retry] = await Promise.all([registry.pollPhoneLogin(start.deviceCode), registry.pollPhoneLogin(start.deviceCode)]);
  expect(first).toEqual(retry);
  expect(await registry.authenticateDevice(first.credential)).toMatchObject({ user_id: 'alice' });
  expect(await registry.authenticateServer(first.credential)).toBeNull();
  expect(await registry.listDevices('alice')).toHaveLength(1);
  expect(await registry.listServers('alice')).toEqual([]);
  const rows = await db.query('SELECT * FROM connect_codes');
  expect(rows[0]).toMatchObject({ hash: digest(start.userCode), device_hash: digest(start.deviceCode), purpose: 'phone-login' });
  expect(JSON.stringify(rows)).not.toContain(first.credential);
  expect((await call('approve', { code: start.userCode, approved: true }, owner)).status).toBe(409);
  await registry.revoke('alice', 'device', first.deviceId);
  expect((await call('poll', { deviceCode: start.deviceCode })).status).toBe(403);
  expect(await registry.listDevices('alice')).toHaveLength(1);
});
it('requires a signed-in browser and same-origin approval, validates inputs and separates computer codes', async () => {
  const start = await registry.startPhoneLogin('Phone');
  expect((await call(`info?code=${start.userCode}`)).status).toBe(401);
  for (const headers of [{}, { cookie }, { cookie, origin: 'https://evil.test' }]) expect((await call('approve', { code: start.userCode, approved: true }, headers)).status).toBe(headers.cookie ? 403 : 401);
  for (const approved of ['yes', null, 1]) expect((await call('approve', { code: start.userCode, approved }, owner)).status).toBe(400);
  expect((await call('approve', { code: 'bad', approved: true }, owner)).status).toBe(400);
  expect((await call('info?code=bad', undefined, owner)).status).toBe(400);
  expect((await call('poll', { deviceCode: 'bad' })).status).toBe(400);
  await expect(registry.pollPhoneLogin('bad')).rejects.toMatchObject({ status: 400 });
  for (const name of ['', '\u0000', 'x'.repeat(81), 12]) expect((await call('start', { name })).status).toBe(400);
  const computer = await registry.startEnrollment('Mac');
  expect((await call(`info?code=${computer.userCode}`, undefined, owner)).status).toBe(410);
  expect((await call('approve', { code: computer.userCode, approved: true }, owner)).status).toBe(409);
  expect((await call('poll', { deviceCode: computer.deviceCode })).status).toBe(410);
});
it('handles denial, expiry, pruning and account capacity without creating an unapproved device', async () => {
  const denied = await registry.startPhoneLogin('Phone');
  await registry.approvePhoneLogin('alice', denied.userCode, false);
  expect(await registry.phoneLoginInfo(denied.userCode)).toMatchObject({ approved: false, denied: true });
  await expect(registry.pollPhoneLogin(denied.deviceCode)).rejects.toMatchObject({ status: 403 });
  const approved = await registry.startPhoneLogin('Phone'); await registry.approvePhoneLogin('alice', approved.userCode, true);
  await registry.pollPhoneLogin(approved.deviceCode);
  const full = await registry.startPhoneLogin('Another'); await registry.approvePhoneLogin('alice', full.userCode, true);
  await expect(registry.pollPhoneLogin(full.deviceCode)).rejects.toMatchObject({ status: 409 });
  now += 600_001;
  await expect(registry.pollPhoneLogin(approved.deviceCode)).rejects.toMatchObject({ status: 410 });
  await expect(registry.phoneLoginInfo(full.userCode)).rejects.toMatchObject({ status: 410 });
  await registry.startPhoneLogin('Fresh');
  expect(await db.query('SELECT * FROM connect_codes')).toHaveLength(1);
});
it('bounds unauthenticated requests and pending records', async () => {
  for (let n = 0; n < 30; n++) expect((await call('start', { name: 'Phone' })).status).toBe(200);
  expect((await call('start', { name: 'Phone' })).status).toBe(429);
  await db.transaction('fixture', async (query: any) => {
    for (let n = 0; n < 970; n++) await query('INSERT INTO connect_codes(hash,purpose,name,expires_at,created_at) VALUES($1,$2,$3,$4,$5)', [String(n), 'phone-login', 'Phone', now + 60_000, now]);
  });
  await expect(registry.startPhoneLogin('Phone')).rejects.toMatchObject({ status: 429 });
});
