import { randomUUID } from 'node:crypto';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { createProjectStore } from './project-store.js';
import { projectOnHost, projectSources } from '@zana-ai/zcc-domain/project';
import type { Project } from '@zana-ai/zcc-domain/product';
import { resolveSpawnChoiceForHost } from './services/threads/spawn-choice-for-host.js';
const dirs: string[] = []; const root = () => { const d = mkdtempSync(join(tmpdir(), 'zana-project-sources-')); dirs.push(d); return d; };
afterEach(() => dirs.splice(0).forEach(d => rmSync(d, { recursive: true, force: true })));
it('keeps one project identity and canonical metadata while adding concurrent host checkouts durably', async () => {
  const dir = root(), original = join(dir, 'repo'); mkdirSync(original);
  const file = join(dir, 'projects.json'), store = createProjectStore({ projectsFile: file });
  const project = await store.add(original), primary = randomUUID(), one = randomUUID(), two = randomUUID();
  await Promise.all([store.addSource(project.id, { hostId: one, path: '/home/one/repo' }, primary), store.addSource(project.id, { hostId: two, path: '/work/two/repo' }, primary)]);
  const saved = createProjectStore({ projectsFile: file }).list()[0]! as Project;
  expect(saved).toMatchObject({ id: project.id, path: project.path, tag: project.tag });
  expect(saved.sources).toHaveLength(2);
  expect(projectSources(saved, primary)).toHaveLength(3);
  const execution = projectOnHost(saved, one, primary);
  expect(execution).toMatchObject({ id: project.id, hostId: one, path: '/home/one/repo' });
  expect(resolveSpawnChoiceForHost({ project: execution, choice: { kind: 'unmanaged' }, executionHostId: one, primaryHostId: primary, remoteToolProxy: false }).ok).toBe(true);
  expect(() => projectOnHost(saved, randomUUID(), primary)).toThrow('Add a checkout');
  expect(saved.path).toBe(project.path);
  await store.addSource(project.id, { hostId: one, path: '/home/one/repo' }, primary);
  expect(store.list()[0]!.sources).toHaveLength(2);
  await store.removeSource(project.id, saved.sources![0]!.id);
  expect(store.list()[0]!.sources).toHaveLength(1);
  expect(readFileSync(file, 'utf8')).toContain(project.id);
});
it('preserves legacy fields and rejects conflicting sources, canonical removal and invalid paths', async () => {
  const dir = root(), file = join(dir, 'projects.json'), primary = randomUUID(), one = randomUUID();
  const legacy = { id: randomUUID(), name: 'Existing', path: '/legacy', createdAt: 1, lastActiveAt: 2, favorite: true, customField: 'preserved' };
  writeFileSync(file, JSON.stringify([legacy]));
  const store = createProjectStore({ projectsFile: file });
  expect(projectSources(legacy, primary)[0]!.id).toBe(`original:${legacy.id}`);
  expect(projectSources(legacy)).toEqual([]);
  await store.addSource(legacy.id, { hostId: one, path: '/remote' }, primary);
  expect(store.list()[0]).toMatchObject(legacy);
  for (const input of [{ hostId: primary, path: '/different' }, { hostId: one, path: '/other' }, { hostId: 'bad', path: '/repo' }, { hostId: one, path: '../repo' }]) await expect(store.addSource(legacy.id, input, primary)).rejects.toThrow();
  await expect(store.removeSource(legacy.id, `original:${legacy.id}`)).rejects.toThrow('metadata');
  await expect(store.removeSource('unknown', 'id')).rejects.toThrow();
  await expect(store.addSource('unknown', { hostId: one, path: '/repo' }, primary)).rejects.toThrow();
  expect((await store.addSource(legacy.id, { hostId: primary, path: '/legacy' }, primary)).path).toBe('/legacy');
});
it('does not register the same host folder under two projects', async () => {
  const dir = root(), store = createProjectStore({ projectsFile: join(dir, 'projects.json') }), primary = randomUUID(), remote = randomUUID();
  const a = await store.add(dir), folder = join(dir, 'second'); mkdirSync(folder); const b = await store.add(folder);
  await store.addSource(a.id, { hostId: remote, path: '/remote' }, primary);
  await expect(store.addSource(b.id, { hostId: remote, path: '/remote' }, primary)).rejects.toThrow('another registered project');
});
