// @vitest-environment happy-dom
import { act,cleanup,render } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { afterEach,expect,it,vi } from 'vitest';
const h=vi.hoisted(() => ({event:(_:any) => {},updated:(_:any) => {},reconnect:() => {},off:vi.fn(),get:vi.fn(),timeline:vi.fn(),upsert:vi.fn()}));
vi.mock('../../lib/product-client.js',() => ({product:{threads:{get:h.get,timeline:h.timeline,onEvent:(fn:any) => {h.event=fn;return h.off;},onUpdated:(fn:any) => {h.updated=fn;return h.off;}}}}));
vi.mock('../../lib/product-ws.js',() => ({subscribeProductReconnect:(fn:any) => {h.reconnect=fn;return h.off;}}));
vi.mock('../../thread-store.js',async original => ({...await original<any>(),useThreads:Object.assign((pick:any) => pick({threads:[],upsert:h.upsert}),{getState:() => ({threads:[],upsert:h.upsert})})}));
vi.mock('../../store.js',() => ({useData:(pick:any) => pick({projects:[]})}));
vi.mock('../../hooks/useRouteState.js',() => ({useRouteState:() => ({threadId:'a',isProjectFocused:false})}));
vi.mock('../../hooks/useCompactLayout.js',() => ({useCompactLayout:() => false}));
vi.mock('../../components/useMobileThreadTitleTarget.js',() => ({useMobileThreadTitleTarget:() => null,useMobileThreadActionsTarget:() => null,useMobileThreadControlsTarget:() => null}));
vi.mock('../../components/thread/secondary-panel/useThreadSecondaryPanel.js',() => ({useThreadSecondaryPanel:() => ({state:{tabs:[],isOpen:false,isMaximized:false,activeId:null},open:() => {}})}));
vi.mock('../../components/thread/secondary-panel/useInAppBrowserPanel.js',() => ({useInAppBrowserPanel:() => {}}));
vi.mock('../../lib/use-desktop-browser-reveal.js',() => ({useDesktopBrowserReveal:() => {}}));
vi.mock('../../components/thread/secondary-panel/useThreadOpenFileSignal.js',() => ({useThreadOpenFileSignal:() => {},dispatchThreadOpenFile:() => {}}));
vi.mock('../../components/thread/secondary-panel/useThreadOpenTerminalSignal.js',() => ({useThreadOpenTerminalSignal:() => {}}));
vi.mock('../thread-detail/PaneContext.js',() => ({useOptionalPaneContext:() => null,usePaneSecondaryPanelRegistration:() => {}}));
vi.mock('../../components/thread/pending-interactions/useOpenPendingInteractions.js',async original => ({...await original<any>(),useOpenPendingInteractions:() => []}));
vi.mock('../../components/ThreadCommandComposer.js',() => ({ThreadCommandComposer:() => null}));
vi.mock('../../components/thread/ThreadTimeline.js',() => ({ThreadTimeline:({rows}:any) => <div>{rows.length} rows</div>}));
vi.mock('../../components/thread/ThreadWorkspaceBanner.js',() => ({ThreadWorkspaceBanner:() => null}));
vi.mock('../../components/thread/ThreadDetailOverflow.js',() => ({ThreadDetailOverflow:() => null}));
vi.mock('../../components/thread/ThreadDetailSearch.js',() => ({ThreadDetailSearch:() => null}));
vi.mock('../../components/thread/timeline/ThreadBanners.js',() => ({ThreadDetailHeading:({title}:any) => <h1>{title}</h1>,ThreadDetailActions:({children}:any) => children,ThreadPromptModeCard:() => null,ThreadStatusBadge:() => null,ThreadTodoCard:() => null}));
vi.mock('../../components/thread/timeline/ComposerStackCards.js',() => ({BackgroundCommandsCard:() => null,ModelFallbackCard:() => null,PromptContextBanner:() => null,QueuedMessagesCard:() => null}));
vi.mock('../../components/thread/pending-interactions/ChildThreadPendingBanners.js',() => ({ChildThreadPendingBanners:() => null}));
vi.mock('../../plugins/PluginThreadHeaderActions.js',() => ({PluginThreadHeaderActions:() => null}));
vi.mock('../../plugins/thread-panel-owner.js',() => ({ThreadPanelOwnerProvider:({children}:any) => children}));
import { ThreadDetail } from './ThreadDetailView.js';
afterEach(() => {cleanup();vi.useRealTimers();vi.clearAllMocks();});
it('wires bounded continuous refresh, matching filters, reconnect and unmount cancellation through the real detail effect',async () => {
  vi.useFakeTimers();
  h.get.mockResolvedValue({thread:{id:'a',title:'Loaded thread',status:'idle',createdAt:1}});
  h.timeline.mockResolvedValue({rows:[],maxSeq:0,status:'idle',activeThinking:null});
  const view=render(<MemoryRouter><ThreadDetail threadId="a" embedded/></MemoryRouter>);
  await act(async () => {});expect(h.get).toHaveBeenCalledTimes(1);expect(h.timeline).toHaveBeenCalledTimes(1);
  act(() => {h.event({threadId:'other',sequence:1});h.updated({id:'other'});vi.advanceTimersByTime(1000);});
  expect(h.get).toHaveBeenCalledTimes(1);
  await act(async () => {for(let index=0;index<20;index++){h.event({threadId:'a',sequence:index+1});vi.advanceTimersByTime(25);await Promise.resolve();}});
  expect(h.get.mock.calls.length).toBeGreaterThanOrEqual(3);
  await act(async () => {h.reconnect();vi.advanceTimersByTime(100);});
  const count=h.get.mock.calls.length;
  act(() => h.event({threadId:'a',sequence:100}));view.unmount();
  await act(async () => vi.advanceTimersByTime(1000));
  expect(h.get).toHaveBeenCalledTimes(count);expect(h.off).toHaveBeenCalledTimes(3);
});
