import { test, expect } from './fixtures/app.js';
test('Settings → Phone prepares an editable mobile installation composer', async ({ app }, testInfo) => {
  const win = app.window;
  const threadsBefore = await win.evaluate(() => window.cc.threads.list());
  await win.getByRole('link', { name: 'Settings', exact: true }).click();
  await win.getByTestId('settings-nav-phone').click();
  const panel = win.locator('.settings-panel--preferences');
  await expect(panel.getByRole('list', { name: 'Phone setup steps' }).getByRole('listitem')).toHaveCount(4);
  const installation = panel.getByRole('region', { name: '1. Install Zana' });
  await expect(installation.getByRole('list', { name: 'Install Zana on iPhone' }).getByRole('listitem')).toHaveCount(3);
  await expect(installation.getByRole('status')).toContainText('Installing TestFlight alone will not install Zana');
  await expect(installation.getByRole('link', { name: 'View TestFlight in the App Store' })).toHaveAttribute('href', 'https://apps.apple.com/app/testflight/id899247664');
  await expect(installation.getByRole('link', { name: 'Get Zana on TestFlight' })).toHaveCount(0);
  await installation.getByText('Install with a USB cable (iPhone or Android)', { exact: true }).click();
  await expect(installation.getByRole('list', { name: 'Install Zana with a USB cable' })).toBeVisible();
  await expect(installation.getByText(/choose an agent, review the request, and click Send/)).toBeVisible();
  await expect(panel.getByText(/Developer Mode, turn it on, restart/)).toBeVisible();
  await expect(panel.getByText(/enable USB debugging/)).toBeVisible();
  await win.screenshot({ path: testInfo.outputPath('phone-installation-guide.png') });

  await panel.getByRole('button', { name: 'Development install with AI', exact: true }).click();
  const composer = win.getByTestId('launch-modal');
  await expect(composer).toBeVisible();
  const prompt = composer.locator('[contenteditable="true"]');
  await expect(prompt).toContainText('Install or update the Zana mobile app on my connected physical phone');
  await expect(prompt).toContainText('existing Apple signing account');
  await expect(prompt).toContainText('authenticated online gateway');
  await expect(composer.getByRole('button', { name: 'Send', exact: true })).toBeEnabled();
  await win.screenshot({ path: testInfo.outputPath('phone-installation-composer.png') });
  await prompt.fill('Install Zana on my connected iPhone.');
  await expect(prompt).toHaveText('Install Zana on my connected iPhone.');
  await win.keyboard.press('Escape');
  await expect(composer).toHaveCount(0);
  await expect(panel.getByRole('switch', { name: 'Enable phone access' })).toHaveCount(0);
  await expect(panel.getByRole('link', { name: 'Get a connect code' })).toBeVisible();
  await expect(panel.getByLabel('Connection method')).toHaveCount(0);
  await expect(panel.getByRole('button', { name: 'Show pairing QR' })).toHaveCount(0);
  await panel.getByRole('button', { name: 'Development install with AI', exact: true }).click();
  await expect(prompt).toContainText('Install or update the Zana mobile app');
  await win.keyboard.press('Escape');
  expect(await win.evaluate(() => window.cc.threads.list())).toEqual(threadsBefore);
});
