// Generated by scripts/sync-mobile-relay.mjs. Edit services/mobile-relay instead.
import { WebSocket } from 'ws';

export const TUNNEL_PATH = '/_relay/connect';
export const LIMITS = { streams: 64, frame: 1500 * 1024, buffer: 4 * 1024 * 1024, request: 32 * 1024 * 1024, response: 64 * 1024 * 1024, chunk: 64 * 1024 };
const REQUEST_HEADERS = new Set(['accept', 'content-type', 'content-length', 'range', 'if-none-match', 'if-modified-since', 'cookie', 'authorization', 'origin', 'sec-fetch-site']);
const RESPONSE_HEADERS = new Set(['content-type', 'content-length', 'content-encoding', 'cache-control', 'etag', 'last-modified', 'content-range', 'accept-ranges', 'location', 'set-cookie', 'vary', 'referrer-policy', 'x-content-type-options', 'content-disposition', 'content-security-policy', 'content-security-policy-report-only', 'x-frame-options', 'strict-transport-security', 'permissions-policy', 'cross-origin-opener-policy', 'cross-origin-resource-policy']);

export function headers(input, response = false) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw new Error('Invalid headers');
  const out = {};
  for (const [key, value] of Object.entries(input)) {
    const name = key.toLowerCase();
    if (!(response ? RESPONSE_HEADERS : REQUEST_HEADERS).has(name)) continue;
    if (typeof value === 'string' && !/[\r\n\0]/.test(value)) out[name] = value;
    else if (response && name === 'set-cookie' && Array.isArray(value) && value.every(v => typeof v === 'string' && !/[\r\n\0]/.test(v))) out[name] = value;
    else throw new Error('Invalid header');
  }
  if (Buffer.byteLength(JSON.stringify(out)) > 32 * 1024) throw new Error('Headers too large');
  return out;
}
export function validPath(path) {
  return typeof path === 'string' && path.length <= 16 * 1024 && path.startsWith('/') && !path.startsWith('//') && !/[\r\n\0\\]/.test(path) && !path.startsWith('/_relay/');
}
export function parseFrame(raw) {
  const frame = JSON.parse(raw.toString());
  if (!frame || typeof frame !== 'object' || typeof frame.type !== 'string' || !Number.isSafeInteger(frame.id) || frame.id < 0 || frame.id > 0xffffffff) throw new Error('Invalid frame');
  return frame;
}
export function send(socket, frame) {
  if (socket.readyState !== WebSocket.OPEN) return false;
  const text = JSON.stringify(frame);
  if (Buffer.byteLength(text) > LIMITS.frame || socket.bufferedAmount + Buffer.byteLength(text) > LIMITS.buffer) {
    socket.terminate();
    return false;
  }
  socket.send(text);
  return true;
}
export function dataFrames(socket, type, id, data) {
  const bytes = Buffer.from(data);
  for (let offset = 0; offset < bytes.length; offset += LIMITS.chunk) {
    if (!send(socket, { type, id, data: bytes.subarray(offset, offset + LIMITS.chunk).toString('base64') })) return false;
  }
  return true;
}
export function bytes(frame, max = LIMITS.chunk) {
  // A flat character scan avoids regex stack growth for megabyte socket frames.
  if (typeof frame.data !== 'string' || frame.data.length > Math.ceil(max / 3) * 4 || /[^A-Za-z0-9+/=]/.test(frame.data)) throw new Error('Invalid data');
  const data = Buffer.from(frame.data, 'base64');
  if (data.length > max || data.toString('base64') !== frame.data) throw new Error('Invalid or oversized data');
  return data;
}
/** Ping frames count as traffic at Heroku's router, including on idle phones. */
export function heartbeat(socket, interval = 20_000) {
  let alive = true;
  const pong = () => { alive = true; };
  socket.on('pong', pong);
  const timer = setInterval(() => {
    if (!alive) { socket.terminate(); return; }
    alive = false;
    if (socket.readyState === WebSocket.OPEN) socket.ping();
  }, interval);
  timer.unref();
  const stop = () => { clearInterval(timer); socket.off('pong', pong); };
  socket.once('close', stop);
  return stop;
}
export function remoteOrigin(value, allowLocal = false) {
  if (typeof value !== 'string' || value.length > 2048) throw new Error('Invalid relay origin');
  const url = new URL(value);
  if (url.origin.length > 2048 || url.username || url.password || url.pathname !== '/' || url.search || url.hash ||
      (url.protocol !== 'https:' && !(allowLocal && url.protocol === 'http:' && ['127.0.0.1', 'localhost', '[::1]'].includes(url.hostname)))) throw new Error('Use an HTTPS origin without a path or credentials');
  return url;
}
export function validToken(token) { return typeof token === 'string' && /^[A-Za-z0-9_-]{43,128}$/.test(token); }
